New major version with several enhancements
FlowingCode/ChatAssistant pull request #16
Opened 2024-09-12 21:57 UTC by mlopezFC

New major version with the following features:
* Use latest wc-chatbot web component version
* Add support for customizing header and footer
* Complete rewrite of the internal chat history, based on vaadin components instead of wc-bubble
* Support for virtual list to avoid performance issues with large chats
* Fixes visual issues when reattaching, maintaining the state
* Support for displaying who is typing and also if a message is being generated (dancing dots)

2024-09-13 23:05 UTC, mlopezFC commented on src/main/java/com/flowingcode/vaadin/addons/chatassistant/ChatMessage.java
> +  }
Done ✔️

2024-09-17 20:26 UTC, paodb requested changes
Left some comments regarding Javadocs. Please check documentation is complete. Follow shared example.

2024-09-17 20:26 UTC, paodb commented on src/main/java/com/flowingcode/vaadin/addons/chatassistant/ChatAssistant.java
> +   * Sets the SubmitListener that will be notified when the user submits a message on the underlying messageInput
Description should end with a dot. There should be a empty line between the description and the tags. Param and return tags should have a brief description also, and shouldn't end with a dot. See documentation https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#format

2024-09-17 20:26 UTC, paodb commented on src/main/java/com/flowingcode/vaadin/addons/chatassistant/ChatAssistant.java
> +  public ChatAssistant(List<Message> messages) {
Add Javadoc

2024-09-17 20:26 UTC, paodb commented on src/main/java/com/flowingcode/vaadin/addons/chatassistant/ChatAssistant.java
> +  public ChatAssistant() {
Add Javadoc

2024-09-17 20:28 UTC, paodb commented
Besides the requested changes, I tested the branch and the upgrade seems okay to me.

2024-09-17 21:45 UTC, mlopezFC commented on src/main/java/com/flowingcode/vaadin/addons/chatassistant/ChatAssistant.java
> +  public ChatAssistant() {
Done ✔️

2024-09-18 14:04 UTC, paodb approved these changes
LGTM

2024-09-18 14:43 UTC, merged